/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as AppLayoutImport } from './routes/_app/layout'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppServerIdLayoutImport } from './routes/_app/$serverId/layout'
import { Route as AppServerIdIndexImport } from './routes/_app/$serverId/index'
import { Route as AppServerIdChatIdImport } from './routes/_app/$serverId/chat/$id'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutRoute = AppLayoutImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppServerIdLayoutRoute = AppServerIdLayoutImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppServerIdIndexRoute = AppServerIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppServerIdLayoutRoute,
} as any)

const AppServerIdChatIdRoute = AppServerIdChatIdImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppServerIdLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/_app/$serverId': {
      id: '/_app/$serverId'
      path: '/$serverId'
      fullPath: '/$serverId'
      preLoaderRoute: typeof AppServerIdLayoutImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/$serverId/': {
      id: '/_app/$serverId/'
      path: '/'
      fullPath: '/$serverId/'
      preLoaderRoute: typeof AppServerIdIndexImport
      parentRoute: typeof AppServerIdLayoutImport
    }
    '/_app/$serverId/chat/$id': {
      id: '/_app/$serverId/chat/$id'
      path: '/chat/$id'
      fullPath: '/$serverId/chat/$id'
      preLoaderRoute: typeof AppServerIdChatIdImport
      parentRoute: typeof AppServerIdLayoutImport
    }
  }
}

// Create and export the route tree

interface AppServerIdLayoutRouteChildren {
  AppServerIdIndexRoute: typeof AppServerIdIndexRoute
  AppServerIdChatIdRoute: typeof AppServerIdChatIdRoute
}

const AppServerIdLayoutRouteChildren: AppServerIdLayoutRouteChildren = {
  AppServerIdIndexRoute: AppServerIdIndexRoute,
  AppServerIdChatIdRoute: AppServerIdChatIdRoute,
}

const AppServerIdLayoutRouteWithChildren =
  AppServerIdLayoutRoute._addFileChildren(AppServerIdLayoutRouteChildren)

interface AppLayoutRouteChildren {
  AppServerIdLayoutRoute: typeof AppServerIdLayoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppServerIdLayoutRoute: AppServerIdLayoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AppLayoutRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/$serverId': typeof AppServerIdLayoutRouteWithChildren
  '/': typeof AppIndexRoute
  '/$serverId/': typeof AppServerIdIndexRoute
  '/$serverId/chat/$id': typeof AppServerIdChatIdRoute
}

export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/': typeof AppIndexRoute
  '/$serverId': typeof AppServerIdIndexRoute
  '/$serverId/chat/$id': typeof AppServerIdChatIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppLayoutRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/$serverId': typeof AppServerIdLayoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/$serverId/': typeof AppServerIdIndexRoute
  '/_app/$serverId/chat/$id': typeof AppServerIdChatIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/onboarding'
    | '/$serverId'
    | '/'
    | '/$serverId/'
    | '/$serverId/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/onboarding' | '/' | '/$serverId' | '/$serverId/chat/$id'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/_app/$serverId'
    | '/_app/'
    | '/_app/$serverId/'
    | '/_app/$serverId/chat/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/onboarding"
      ]
    },
    "/_app": {
      "filePath": "_app/layout.tsx",
      "children": [
        "/_app/$serverId",
        "/_app/"
      ]
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/_app/$serverId": {
      "filePath": "_app/$serverId/layout.tsx",
      "parent": "/_app",
      "children": [
        "/_app/$serverId/",
        "/_app/$serverId/chat/$id"
      ]
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/$serverId/": {
      "filePath": "_app/$serverId/index.tsx",
      "parent": "/_app/$serverId"
    },
    "/_app/$serverId/chat/$id": {
      "filePath": "_app/$serverId/chat/$id.tsx",
      "parent": "/_app/$serverId"
    }
  }
}
ROUTE_MANIFEST_END */
